server:
  port: 8010

spring:
  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: 47.105.146.74:8848

#    alibaba:
#      seata:
#        tx-service-group: sunrise_tx_group

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.146.74:3306/ac_mall_cloud_user_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =GMT%2B8
    username: user_service_u
    password: user_service_PWD_123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: user-service
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true    #开启数据库代理
  config:
    type: nacos
    nacos:
      namespace:
      server-addr: 47.105.146.74:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 47.105.146.74:8848
      namespace: public
      username: nacos
      password: nacos

  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091