server:
  port: 8020

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        server-addr: 47.105.146.74:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8888

    alibaba:
      seata:
        tx-service-group: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.146.74:3306/ac_mall_cloud_order_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =GMT%2B8
    username: order_service_u
    password: order_service_PWD_123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  sentinel:
    #为feign整合Sentinel
    enabled: true

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 25000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 25000

#seata:
#  client:
#    support:
#      spring:
#        datasource-autoproxy: true
#  tx-service-group: order
#  service:
#    grouplist: 127.0.0.1:8091